<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\AttendanceRecord;
use App\Models\OvertimeRequest;
use Carbon\Carbon;

class AttendanceOvertimeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = Employee::all();
        if ($employees->isEmpty()) {
            return;
        }

        foreach ($employees as $employee) {
            // Generate attendance for the last 5 days
            for ($i = 0; $i < 5; $i++) {
                $date = Carbon::now()->subDays($i)->format('Y-m-d');
                
                AttendanceRecord::updateOrCreate([
                    'employee_id' => $employee->id,
                    'date' => $date,
                ], [
                    'clock_in' => '08:00',
                    'clock_out' => '17:00',
                    'status' => 'hadir',
                    'remarks' => 'Generated by seeder'
                ]);

                // 20% chance to have an overtime request on this day
                if (rand(1, 100) <= 20) {
                    OvertimeRequest::create([
                        'employee_id' => $employee->id,
                        'date' => $date,
                        'duration_minutes' => rand(60, 180),
                        'reason' => 'Urgent deadline ' . $date,
                        'status' => 'PENDING_MANAGER'
                    ]);
                }
            }
        }
    }
}
