<x-app>
  <x-slot:title>Payroll Runs</x-slot:title>

<div class="pagetitle">
  <h1>Payroll Runs</h1>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{{ route('dashboard.index') }}">Home</a></li>
      <li class="breadcrumb-item active">Payroll Runs</li>
    </ol>
  </nav>
</div>

<section class="section">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Payroll Periods</h5>
          
          <div class="mb-3">
              @can('create-payroll-runs')
              <a href="{{ route('payroll-runs.create') }}" class="btn btn-primary"><i class="bi bi-play-fill me-1"></i> Generate Payroll</a>
              @endcan
          </div>

          @if(session('success'))
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ session('success') }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          @endif
          
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Period</th>
                <th>Status</th>
                <th>Generated By</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              @forelse($payroll_runs as $run)
              <tr>
                <td>{{ date("F", mktime(0, 0, 0, $run->period_month, 1)) }} {{ $run->period_year }}</td>
                <td>
                    @if($run->status === 'DRAFT')
                        <span class="badge bg-secondary">DRAFT</span>
                    @elseif($run->status === 'PENDING_FINANCE')
                        <span class="badge bg-warning text-dark">PENDING FINANCE</span>
                    @elseif($run->status === 'APPROVED')
                        <span class="badge bg-primary">APPROVED</span>
                    @elseif($run->status === 'PAID')
                        <span class="badge bg-success">PAID</span>
                    @endif
                </td>
                <td>{{ $run->creator->name ?? '-' }}</td>
                <td>
                  <div class="d-flex gap-1">
                    <a href="{{ route('payroll-runs.show', $run->id) }}" class="btn btn-sm btn-info text-white"><i class="bi bi-eye"></i> View Details</a>
                  </div>
                </td>
              </tr>
              @empty
              <tr>
                <td colspan="4" class="text-center">No payroll runs found.</td>
              </tr>
              @endforelse
            </tbody>
          </table>
          
        </div>
      </div>
    </div>
  </div>
</section>
</x-app>
